### PR TITLE
Some updates

### PR DESCRIPTION
**Pull request by JackMD**
Hey,
Simple and clean plugin, just needed some formatting also don't add spaces in plugin's name in `plugin.yml`. Also no need for multiple `3.0.0, 3.0.1, 3.0.2, 3.1.0 etc` as of the latest versioning scheme adopted by PocketMine-MP every plugin of api 3.0.0 will work on 3.x.x unless you require a particular api change.

### CODE REVIEW

**Comment by Aericio** [comment]
You shouldn’t change the formatting. It’s how PHPStorm formats on 7.2, and author is using that formatting style.

**Comment by JackMD** [comment]
@Aericio type CTRL + ALT + SHIFT + L into PhpStorm and then restyle it you will see the difference..

**Comment by Aericio** [comment]
Aren’t you on an older version of PHPStorm? I’m on latest, and on 7.2, and that is the auto format style. 

And again, you shouldn’t change the formatting of the author’s code. It’s up to them how it’s formatted. Unless it’s actually messed up where it’s an eyesore to read, no point in changing their formatting style.

**Comment by JackMD** [comment]
You win I lose, End of conversation.

**Comment by Saini14** [comment]
what is happening

**Pull request closed without merging**
